
// Code generated by gox; DO NOT EDIT.
package gox
import (
)

var IndexList = map[string]string{
}

var PagesList = map[string]PageData{
}

var DataList = map[string]DataRender{
	
}

var RenderList = []RenderDefault{
	
}

var HandleList = []HandlerDefault{
	
}
